/* eslint-disable */
import React from 'react'

export const ConverterTab: React.FC<{ conv: any, t: any, colors: any, isDark: boolean }> = ({ conv, t, colors }) => (
  <div className={`w-full flex-1 border rounded-3xl p-8 flex flex-col gap-6 overflow-y-auto ${colors.c_bgPanel}`}>
    <div><h3 className="text-2xl font-bold mb-1 flex items-center gap-2">{t('convTitle')}</h3><p className={`text-sm ${colors.c_textSub}`}>{t('convSub')}</p></div>
    <div className="grid grid-cols-2 gap-6 w-full">
      <div className="flex flex-col gap-2"><label className={`text-sm font-medium ${colors.c_textSub}`}>{t('convLabelFile')}</label><div className="flex items-center gap-2"><input type="text" readOnly value={conv.convertFile || "Select File Source..."} className={`flex-1 border rounded-xl px-4 py-3 text-xs truncate focus:outline-none ${colors.c_bgInput}`} /><button disabled={conv.isConverting} onClick={async () => { const path = await window.electron.ipcRenderer.invoke('open-file-dialog', null); if (path) conv.setConvertFile(path); }} className={`text-xs font-bold px-4 py-3 rounded-xl shrink-0 border ${colors.c_btnSec}`}>{t('btnChooseFile')}</button></div></div>
      <div className="flex flex-col gap-2"><label className={`text-sm font-medium ${colors.c_textSub}`}>{t('convLabelSub')}</label><div className="flex items-center gap-2"><input type="text" readOnly value={conv.convertSub || t('convNoSub')} className={`flex-1 border rounded-xl px-4 py-3 text-xs truncate focus:outline-none ${colors.c_bgInput}`} /><button disabled={conv.isConverting} onClick={async () => { const path = await window.electron.ipcRenderer.invoke('open-file-dialog', { name: 'Subtitles', extensions: ['srt', 'ass'] }); if (path) conv.setConvertSub(path); }} className={`text-xs font-bold px-4 py-3 rounded-xl shrink-0 border ${colors.c_btnSec}`}>{t('btnChooseSub')}</button>{conv.convertSub && <button onClick={() => conv.setConvertSub('')} className="text-xs text-red-500 font-bold px-2 hover:text-red-400">{t('btnDelete')}</button>}</div></div>
    </div>
    <div className={`grid grid-cols-2 gap-6 w-full border-t pt-4 ${colors.c_borderT}`}>
      <div className="flex flex-col gap-2">
        <label className={`text-sm font-medium ${colors.c_textSub}`}>{t('convLabelTarget')}</label>
        <select value={conv.targetExtension} onChange={(e) => conv.setTargetExtension(e.target.value)} className={`border text-sm rounded-xl px-4 py-3 focus:border-red-500 focus:outline-none w-full ${colors.c_bgInput}`}><optgroup label="Video Container"><option value="mp4">Video MP4</option><option value="mkv">Video MKV</option><option value="mov">Video MOV</option></optgroup><optgroup label="Image Extension"><option value="png">Ảnh PNG</option><option value="jpg">Ảnh JPG</option><option value="webp">Ảnh WebP</option><option value="mp3">Âm thanh MP3</option><option value="m4a">Âm thanh M4A</option></optgroup><optgroup label="Trích xuất phụ đề AI (Groq Whisper)"><option value="srt">SubRip Subtitle (.srt)</option><option value="vtt">WebVTT Subtitle (.vtt)</option><option value="ass">Advanced SubStation (.ass)</option></optgroup></select>
      </div>
      <div className="flex flex-col gap-2"><label className={`text-sm font-medium ${colors.c_textSub}`}>{t('convLabelSave')}</label><div className="flex items-center gap-2"><input type="text" readOnly value={conv.convertFolder || t('convDefaultDir')} className={`flex-1 border rounded-xl px-4 py-3 text-xs truncate focus:outline-none ${colors.c_bgInput}`} /><button disabled={conv.isConverting} onClick={async () => { const path = await window.electron.ipcRenderer.invoke('open-folder-dialog'); if (path) conv.setConvertFolder(path); }} className={`text-xs font-bold px-4 py-3 rounded-xl transition-colors shrink-0 ${colors.c_btnSec}`}>{t('btnChooseFolder')}</button></div></div>
    </div>
    {conv.isConverting && ( <div className="bg-red-500/5 border border-red-500/20 rounded-xl p-4 w-full"><div className="flex justify-between items-center mb-2"><span className="text-xs font-medium animate-pulse">{conv.convMsg}</span><span className="text-xs font-bold text-red-500">{conv.convPercent}%</span></div><div className={`w-full h-2 rounded-full overflow-hidden ${colors.c_bgInput}`}><div className="bg-gradient-to-r from-red-600 to-red-500 h-full" style={{ width: `${conv.convPercent}%` }}></div></div></div> )}
    <button onClick={conv.handleConvertFile} disabled={conv.isConverting} className={`w-full font-bold py-4 rounded-xl text-lg transition-all mt-auto ${conv.isConverting ? 'bg-zinc-600 text-zinc-400' : 'bg-red-600 hover:bg-red-500 text-white shadow-[0_0_25px_rgba(220,38,38,0.15)]'}`}>{conv.isConverting ? t('converting') : t('convert')}</button>
  </div>
)