/* eslint-disable */
import React from 'react'

export const DownloaderTab: React.FC<{ dl: any, t: any, colors: any }> = ({ dl, t, colors }) => (
  <div className={`w-full flex-1 border rounded-3xl p-8 flex flex-col gap-6 overflow-y-auto select-none ${colors.c_bgPanel}`}>
    <div><h3 className="text-2xl font-bold mb-1 flex items-center gap-2">{t('dlTitle')}</h3><p className={`text-sm ${colors.c_textSub}`}>{t('dlSub')}</p></div>
    <div className="flex flex-col gap-2 w-full"><label className={`text-sm font-medium ${colors.c_textSub}`}>{t('dlLabelUrl')}</label><input type="text" disabled={dl.isDownloading} value={dl.downloadUrl} onChange={(e) => dl.setDownloadUrl(e.target.value)} placeholder="https://www.youtube.com/watch?v=..." className={`w-full border focus:border-red-500 rounded-xl px-4 py-3.5 focus:outline-none ${colors.c_bgInput}`} /></div>
    <div className="grid grid-cols-3 gap-6 w-full">
      <div className="flex flex-col gap-2"><label className={`text-sm font-medium ${colors.c_textSub}`}>{t('dlLabelRes')}</label><select disabled={dl.isDownloading} value={dl.dlResolution} onChange={(e) => dl.setDlResolution(e.target.value)} className={`border text-sm rounded-xl px-4 py-3 focus:border-red-500 focus:outline-none w-full ${colors.c_bgInput}`}><option value="best">{t('dlBest')}</option><option value="2160">4K 2160p</option><option value="1440">2K 1440p</option><option value="1080">FullHD 1080p</option><option value="720">HD 720p</option></select></div>
      <div className="flex flex-col gap-2"><label className={`text-sm font-medium ${colors.c_textSub}`}>{t('dlLabelCut')}</label><div className="flex items-center gap-2 w-full"><input type="text" placeholder="0:10" disabled={dl.isDownloading} value={dl.dlStart} onChange={(e) => dl.setDlStart(e.target.value)} className={`w-full border focus:border-red-500 rounded-xl px-3 py-3 text-sm text-center focus:outline-none ${colors.c_bgInput}`} /><span className="text-gray-600">-</span><input type="text" placeholder="2:30" disabled={dl.isDownloading} value={dl.dlEnd} onChange={(e) => dl.setDlEnd(e.target.value)} className={`w-full border focus:border-red-500 rounded-xl px-3 py-3 text-sm text-center focus:outline-none ${colors.c_bgInput}`} /></div></div>
      <div className="flex flex-col gap-2"><label className={`text-sm font-medium ${colors.c_textSub}`}>{t('dlLabelSave')}</label><div className="flex items-center gap-2 w-full"><input type="text" readOnly value={dl.downloadFolder || t('dlDefaultDir')} className={`flex-1 border rounded-xl px-4 py-3 text-sm truncate focus:outline-none ${colors.c_bgInput}`} /><button disabled={dl.isDownloading} onClick={async () => { const path = await window.electron.ipcRenderer.invoke('open-folder-dialog'); if (path) dl.setDownloadFolder(path); }} className={`border text-sm font-bold px-4 py-3 rounded-xl transition-colors shrink-0 ${colors.c_btnSec}`}>{t('btnChooseFolder')}</button></div></div>
    </div>
    {dl.isDownloading && ( <div className="bg-red-500/5 border border-red-500/20 rounded-xl p-4 w-full"><div className="flex justify-between items-center mb-2"><span className="text-xs font-medium animate-pulse">{dl.dlMsg}</span><span className="text-xs font-bold text-red-500">{dl.dlPercent}%</span></div><div className={`w-full h-2 rounded-full overflow-hidden ${colors.c_bgInput}`}><div className="bg-red-500 h-full" style={{ width: `${dl.dlPercent}%` }}></div></div></div> )}
    <button onClick={dl.handleDownloadVideo} disabled={dl.isDownloading} className={`w-full font-bold py-4 rounded-xl text-lg transition-all mt-auto ${dl.isDownloading ? 'bg-zinc-600 text-zinc-400 cursor-not-allowed' : 'bg-red-600 hover:bg-red-500 text-white shadow-[0_0_25px_rgba(220,38,38,0.15)]'}`}>{dl.isDownloading ? t('downloading') : t('download')}</button>
  </div>
)