/* eslint-disable */
import React from 'react'
import { AVAILABLE_APPS } from '../constants/apps'

export const InstallerTab: React.FC<{ ins: any, t: any, colors: any, isDark: boolean, platform: string }> = ({ ins, t, colors, isDark, platform }) => (
  <div className={`w-full flex-1 border rounded-3xl p-8 flex flex-col gap-6 overflow-y-auto ${colors.c_bgPanel}`}>
    <div><h3 className="text-2xl font-bold mb-1 flex items-center gap-2">{t('insTitle')}</h3><p className={`text-sm ${colors.c_textSub}`}>{t('insSub')} <span className="text-red-500 font-bold uppercase">{t('insCore', { core: platform === 'darwin' ? 'macOS Homebrew' : 'Windows Winget' })}</span></p></div>
    <div className={`p-4 rounded-2xl border flex items-center gap-3 ${colors.c_bgTab}`}><input type="text" value={ins.searchQuery} disabled={ins.isInstalling || ins.isSearching} onChange={(e) => ins.setSearchQuery(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && ins.handleSearchAppOnline()} placeholder={platform === 'darwin' ? t('insSearchMac') : t('insSearchWin')} className={`flex-1 border rounded-xl px-4 py-2.5 text-sm font-semibold focus:border-red-500 focus:outline-none transition-colors placeholder-zinc-400 ${colors.c_bgInput}`} /><button onClick={ins.handleSearchAppOnline} disabled={ins.isInstalling || ins.isSearching} className="bg-red-600 hover:bg-red-500 text-white font-bold text-sm px-6 py-2.5 rounded-xl transition-all disabled:bg-zinc-600">{ins.isSearching ? t('insSearching') : t('insSearchBtn')}</button></div>
    {ins.searchResults.length > 0 && (
      <div className="flex flex-col gap-2"><span className="text-sm font-bold text-red-500">{t('insSearchResult')}</span>
        <div className="grid grid-cols-[repeat(auto-fit,minmax(240px,1fr))] gap-4 w-full">{ins.searchResults.map((item: any) => { const isChecked = ins.selectedApps.includes(item.id); return ( <div key={item.id} onClick={() => !ins.isInstalling && ins.toggleAppSelection(item.id)} className={`border p-4 rounded-2xl cursor-pointer flex items-center gap-3 transition-all select-none ${isChecked ? 'border-red-500 bg-red-500/5' : isDark ? 'border-[#262626] hover:bg-zinc-800' : 'border-zinc-200 hover:bg-zinc-50'}`}><div className={`w-5 h-5 border rounded flex items-center justify-center text-xs ${colors.c_bgInput}`}>{isChecked && <span className="text-red-500 font-bold">✓</span>}</div><div className="flex flex-col min-w-0 flex-1"><span className="text-xs font-bold text-zinc-500 truncate">{item.id}</span><span className="text-sm font-bold truncate text-red-500">{item.name}</span></div></div> ) })}</div>
      </div>
    )}
    <div className="flex flex-col gap-2 border-t pt-4 border-zinc-500/10"><span className={`text-sm font-bold ${colors.c_textSub}`}>{t('insRecommended')}</span>
      <div className="grid grid-cols-[repeat(auto-fit,minmax(240px,1fr))] gap-4 w-full">{AVAILABLE_APPS.map((item: any) => { const targetId = platform === 'darwin' ? item.macId : item.id; const isChecked = ins.selectedApps.includes(targetId); return ( <div key={targetId} onClick={() => !ins.isInstalling && ins.toggleAppSelection(targetId)} className={`border p-4 rounded-2xl cursor-pointer flex items-center gap-3 transition-all select-none ${isChecked ? 'border-red-500 bg-red-500/5' : isDark ? 'border-[#262626] hover:bg-zinc-800' : 'border-zinc-200 hover:bg-zinc-50'}`}><div className={`w-5 h-5 border rounded flex items-center justify-center text-xs ${colors.c_bgInput}`}>{isChecked && <span className="text-red-500 font-bold">✓</span>}</div><div className="flex flex-col min-w-0"><span className="text-xl mb-0.5">{item.icon}</span><span className="text-sm font-semibold truncate">{item.name}</span><span className="text-[10px] text-zinc-500 truncate">{targetId}</span></div></div> ) })}</div>
    </div>
    {ins.isInstalling && ( <div className={`bg-gradient-to-br ${isDark ? 'from-[#1a1a1a] to-[#121212] border-zinc-800' : 'from-zinc-50 to-zinc-100 border-zinc-200'} border rounded-2xl p-6 w-full mt-auto flex flex-col gap-4 shadow-inner`}><div className="flex flex-col gap-1"><div className="flex justify-between items-center text-xs font-semibold"><span className="text-red-500 animate-pulse">{t('insProgressApp', { index: ins.installProgress.appIndex, total: ins.installProgress.totalApps, name: ins.installProgress.appName })}</span><span className={`${isDark ? 'text-gray-400' : 'text-zinc-600'}`}><span className="text-red-500 font-bold">{ins.installProgress.stage} ({ins.installProgress.stagePercent}%)</span></span></div><div className={`w-full h-1.5 rounded-full overflow-hidden ${colors.c_bgInput}`}><div className="bg-red-500 h-full transition-all duration-300" style={{ width: `${ins.installProgress.stagePercent}%` }}></div></div></div><div className="flex flex-col gap-1 border-t pt-3 border-zinc-500/10"><div className="flex justify-between items-center text-xs font-semibold"><span className={`${colors.c_textSub}`}>{t('insProgressGlobal')}</span><span className="text-red-500 font-bold">{ins.installProgress.globalPercent}%</span></div><div className={`w-full h-2 rounded-full overflow-hidden ${colors.c_bgInput}`}><div className="bg-gradient-to-r from-red-600 to-orange-500 h-full transition-all duration-200" style={{ width: `${ins.installProgress.globalPercent}%` }}></div></div></div></div> )}
    <button onClick={ins.handleLaunchInstallation} disabled={ins.isInstalling} className={`w-full font-bold py-4 rounded-xl text-lg transition-all mt-auto ${ins.isInstalling ? 'bg-zinc-600 text-zinc-400 cursor-not-allowed' : 'bg-red-600 hover:bg-red-500 text-white shadow-[0_0_25px_rgba(220,38,38,0.15)]'}`}>{ins.isInstalling ? t('insProcessing') : t('insBtn')}</button>
  </div>
)